# Generated by Django 3.2.5 on 2021-07-20 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=1024)),
                ('old_address', models.CharField(max_length=1024)),
                ('private_area', models.FloatField(default=0.0)),
                ('public_area', models.FloatField(default=0.0)),
                ('households', models.IntegerField(default=0)),
                ('targetholds', models.IntegerField(default=0)),
                ('completion_date', models.DateField()),
                ('floor_area_ratio', models.FloatField(default=0.0)),
                ('building_cover_ratio', models.FloatField(default=0.0)),
                ('construction_company', models.CharField(max_length=128)),
                ('floor', models.IntegerField(default=0)),
                ('top_floor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.IntegerField()),
                ('share_rate', models.FloatField()),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thorny_road.collateral')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
